let
    Source = Csv.Document(File.Contents("\\10.181.250.00\Exports\BDAR\BRANCHREP1.CSV"),[Delimiter=",", Columns=4, Encoding=1252, QuoteStyle=QuoteStyle.None]),
    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Region", Int64.Type}, {"Branch", type text}, {"Rep", type text}, {"Region_1", Int64.Type}}),
    #"Removed Duplicates" = Table.Distinct(#"Changed Type", {"Branch"}),
    #"Reordered Columns" = Table.ReorderColumns(#"Removed Duplicates",{"Rep", "Branch", "Region", "Region_1"}),
    #"Replaced Value" = Table.ReplaceValue(#"Reordered Columns","ZZ","00",Replacer.ReplaceText,{"Rep"}),
    #"Sorted Rows" = Table.Sort(#"Replaced Value",{{"Rep", Order.Ascending}}),
    #"Changed Type1" = Table.TransformColumnTypes(#"Sorted Rows",{{"Rep", Int64.Type}}),
    #"Filtered Rows" = Table.SelectRows(#"Changed Type1", each ([Rep] <> null)),
    #"Removed Columns" = Table.RemoveColumns(#"Filtered Rows",{"Region_1"}),
    #"Merged Queries" = Table.NestedJoin(#"Removed Columns", {"Rep"}, #"514MANDJ1DJ", {"Rep"}, "514MANDJ1DJ", JoinKind.LeftOuter),
    #"Aggregated 514MANDJ1DJ" = Table.AggregateTableColumn(#"Merged Queries", "514MANDJ1DJ", {{"Branch", List.NonNullCount, "Count of Branch"}}),
    #"Renamed Columns" = Table.RenameColumns(#"Aggregated 514MANDJ1DJ",{{"Count of Branch", "A1. O/S Managers Acc"}}),
    #"Merged Queries1" = Table.NestedJoin(#"Renamed Columns", {"Rep"}, NOTPAID, {"Rep"}, "NOTPAID", JoinKind.LeftOuter),
    #"Aggregated NOTPAID" = Table.AggregateTableColumn(#"Merged Queries1", "NOTPAID", {{"Branch", List.NonNullCount, "Count of Branch"}}),
    #"Renamed Columns1" = Table.RenameColumns(#"Aggregated NOTPAID",{{"Count of Branch", "A2. O/S Paylater Acc"}}),
    #"Merged Queries2" = Table.NestedJoin(#"Renamed Columns1", {"Branch"}, CASHCOLLECTION, {"Branch"}, "CASHCOLLECTION", JoinKind.LeftOuter),
    #"Aggregated CASHCOLLECTION" = Table.AggregateTableColumn(#"Merged Queries2", "CASHCOLLECTION", {{"Branch", List.NonNullCount, "Count of CASHCOLLECTION.Branch"}}),
    #"Renamed Columns2" = Table.RenameColumns(#"Aggregated CASHCOLLECTION",{{"Count of CASHCOLLECTION.Branch", "A3. Cash Collection"}}),
    #"Merged Queries3" = Table.NestedJoin(#"Renamed Columns2", {"Branch"}, MEMOSL, {"Branch"}, "MEMOSL", JoinKind.LeftOuter),
    #"Aggregated MEMOSL" = Table.AggregateTableColumn(#"Merged Queries3", "MEMOSL", {{"Branch", List.NonNullCount, "Count of Branch"}}),
    #"Merged Queries4" = Table.NestedJoin(#"Aggregated MEMOSL", {"Branch"}, INVOICESTOP, {"Branch"}, "INVOICESTOP", JoinKind.LeftOuter),
    #"Aggregated INVOICESTOP" = Table.AggregateTableColumn(#"Merged Queries4", "INVOICESTOP", {{"Branch", List.NonNullCount, "Count of Branch.1"}}),
    #"Renamed Columns3" = Table.RenameColumns(#"Aggregated INVOICESTOP",{{"Count of Branch", "A4. Unpaid Invoices"}, {"Count of Branch.1", "A5. Acct off stop then inv"}}),
    #"Merged Queries5" = Table.NestedJoin(#"Renamed Columns3", {"Branch"}, CRNREBOOK, {"Branch"}, "CRNREBOOK", JoinKind.LeftOuter),
    #"Aggregated CRNREBOOK" = Table.AggregateTableColumn(#"Merged Queries5", "CRNREBOOK", {{"Branch", List.NonNullCount, "Count of Branch"}}),
    #"Renamed Columns4" = Table.RenameColumns(#"Aggregated CRNREBOOK",{{"Count of Branch", "A6. Crn 3 days sell 1 day"}}),
    #"Merged Queries6" = Table.NestedJoin(#"Renamed Columns4", {"Branch"}, QUOTESTOP, {"Branch"}, "QUOTESTOP", JoinKind.LeftOuter),
    #"Aggregated QUOTESTOP" = Table.AggregateTableColumn(#"Merged Queries6", "QUOTESTOP", {{"Branch", List.NonNullCount, "Count of Branch"}}),
    #"Renamed Columns5" = Table.RenameColumns(#"Aggregated QUOTESTOP",{{"Count of Branch", "A7. Quote acct on stop"}}),
    #"Merged Queries7" = Table.NestedJoin(#"Renamed Columns5", {"Branch"}, MANSALESSTOP, {"Branch"}, "MANSALESSTOP", JoinKind.LeftOuter),
    #"Aggregated MANSALESSTOP" = Table.AggregateTableColumn(#"Merged Queries7", "MANSALESSTOP", {{"Branch", List.NonNullCount, "Count of Branch"}}),
    #"Renamed Columns6" = Table.RenameColumns(#"Aggregated MANSALESSTOP",{{"Count of Branch", "A8. MAN sale acct stop"}}),
    #"Merged Queries8" = Table.NestedJoin(#"Renamed Columns6", {"Branch"}, CRNINV, {"Branch"}, "CRNINV", JoinKind.LeftOuter),
    #"Aggregated CRNINV" = Table.AggregateTableColumn(#"Merged Queries8", "CRNINV", {{"Branch", List.NonNullCount, "Count of Branch"}}),
    #"Renamed Columns7" = Table.RenameColumns(#"Aggregated CRNINV",{{"Count of Branch", "A9. Crn used INV unpaid"}}),
    #"Merged Queries9" = Table.NestedJoin(#"Renamed Columns7", {"Branch"}, CREDITREBOOK, {"Branch"}, "CREDITREBOOK", JoinKind.LeftOuter),
    #"Aggregated CREDITREBOOK" = Table.AggregateTableColumn(#"Merged Queries9", "CREDITREBOOK", {{"Branch", List.NonNullCount, "Count of Branch"}}),
    #"Renamed Columns8" = Table.RenameColumns(#"Aggregated CREDITREBOOK",{{"Count of Branch", "A10. Credit and Rebook"}}),
    #"Changed Type2" = Table.TransformColumnTypes(#"Renamed Columns8",{{"A1. O/S Managers Acc", Int64.Type}, {"A2. O/S Paylater Acc", Int64.Type}, {"A3. Cash Collection", Int64.Type}, {"A4. Unpaid Invoices", Int64.Type}, {"A5. Acct off stop then inv", Int64.Type}, {"A6. Crn 3 days sell 1 day", Int64.Type}, {"A7. Quote acct on stop", Int64.Type}, {"A8. MAN sale acct stop", Int64.Type}, {"A9. Crn used INV unpaid", Int64.Type}, {"A10. Credit and Rebook", Int64.Type}}),
    #"Sorted Rows1" = Table.Sort(#"Changed Type2",{{"Rep", Order.Ascending}}),
    #"Removed Duplicates1" = Table.Distinct(#"Sorted Rows1", {"Rep"}),
    #"Trimmed Text" = Table.TransformColumns(#"Removed Duplicates1",{{"Branch", Text.Trim, type text}})
in
    #"Trimmed Text"